import { BookOpen, Clock, AlertTriangle } from 'lucide-react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Separator } from '@/components/ui/separator'
import { getPlaybooks } from '@/lib/api'

export const metadata = { title: 'Playbooks — Bruce' }

export default async function PlaybooksPage() {
  let playbooks: {
    id: string
    title: string
    severity: string
    rootCause: string
    steps: string[]
    generatedAt: string
  }[] = []

  try {
    const data = await getPlaybooks()
    playbooks = data.playbooks
  } catch {
    // API unavailable
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold md:text-3xl">Playbooks</h1>
        <p className="text-muted-foreground mt-1">AI-generated fix playbooks from Gemini diagnostics.</p>
      </div>

      <div className="grid gap-4 grid-cols-2 md:grid-cols-3">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Playbooks</CardTitle>
            <BookOpen className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{playbooks.length}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Critical</CardTitle>
            <AlertTriangle className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-red-600">
              {playbooks.filter((p) => p.severity === 'ERROR' || p.severity === 'CRITICAL').length}
            </div>
          </CardContent>
        </Card>
        <Card className="col-span-2 md:col-span-1">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Generated By</CardTitle>
            <Clock className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-sm font-medium">gemini-3.5-flash</div>
            <p className="text-xs text-muted-foreground">via Agent Builder</p>
          </CardContent>
        </Card>
      </div>

      {playbooks.length === 0 ? (
        <Card>
          <CardContent className="py-12 text-center">
            <BookOpen className="mx-auto h-12 w-12 text-muted-foreground mb-4" />
            <h3 className="text-lg font-medium">No playbooks yet</h3>
            <p className="text-sm text-muted-foreground mt-1">
              Playbooks are automatically generated when alerts are triggered. Send a test alert to see one appear here.
            </p>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-4">
          {playbooks.map((playbook, index) => (
            <Card key={playbook.id || index}>
              <CardHeader>
                <div className="flex items-start justify-between gap-4">
                  <div>
                    <CardTitle className="text-lg">{playbook.title}</CardTitle>
                    <CardDescription className="mt-1">{playbook.rootCause}</CardDescription>
                  </div>
                  <Badge variant={
                    playbook.severity === 'ERROR' || playbook.severity === 'CRITICAL' ? 'destructive' : 'secondary'
                  }>
                    {playbook.severity}
                  </Badge>
                </div>
              </CardHeader>
              <CardContent>
                <Separator className="mb-4" />
                <h4 className="text-sm font-medium mb-2">Remediation Steps</h4>
                <ol className="list-decimal pl-5 space-y-1">
                  {playbook.steps.map((step, i) => (
                    <li key={i} className="text-sm text-muted-foreground">{step}</li>
                  ))}
                </ol>
                <p className="text-xs text-muted-foreground mt-4">
                  Generated at {new Date(playbook.generatedAt).toLocaleString()}
                </p>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  )
}
